services:
  dev:
    build: .
    volumes:
      - type: bind
        source: ../
        target: /workspace
        read_only: false
      - type: bind
        source: ../dev
        target: /workspace/dev
        read_only: true
      - type: bind
        source: ./setup
        target: /setup
        read_only: true
      - type: bind
        source: ./nvim
        target: /home/node/.config/nvim
        read_only: false
      - type: bind
        source: ./cache/nvim
        target: /home/node/.local/share/nvim
        read_only: false
      #- type: bind
      #  source: /var/run/docker.sock
      #  target: /var/run/docker.sock
    command: /bin/bash -c "echo ready; sleep infinity"
